HAPPY = 'Felicidad'
ANGRY = 'Molesto'
SURPRISE = 'Sorpresa'
SAD = 'Tristeza'

ALL = [HAPPY, ANGRY, SURPRISE, SAD]

HORIZONTAL_DIMENSION = 40
VERTICAL_DIMENSION = 40
DIMENSIONS = (HORIZONTAL_DIMENSION, VERTICAL_DIMENSION)